### ISSUE TITLE
Improve the graphics of the app

### ISSUE THREAD

**Issue by LolloneS** [LolloneS/blockchain-parser#1]
As of now, the app has no style at all. Some simple flavor shall be added, for example using some basic Bootstrap elements such as buttons and text fields.

**Comment by mahmoudrlx** [comment]
Windows does not support Gunicorn to work with the application
Any solutions?

**Comment by NorisM96** [comment]
Unfortunately, the only solution is to use a virtual machine with Linux or a Dual Boot, however you can process the index.html page like a normal html page.
So for now focus on decorating the index.html page.

**Comment by mahmoudrlx** [comment]
I attached CSS file with index page, please tell me if you like it or not, and I will change it
also please test it on the application.

CIAO

**Comment by mahmoudrlx** [comment]
[layout.zip](https://github.com/LolloneS/blockchain-parser/files/2999524/layout.zip)

**Comment by mahmoudrlx** [comment]
I attached CSS file with index page, please test it on the application, and tell me if you like it or not, so I can change it.
Ciao

**Comment by mahmoudrlx** [comment]
[layout.zip](https://github.com/LolloneS/blockchain-parser/files/3013476/layout.zip)
